import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(override=True)

PROJECT_ROOT = Path(__file__).resolve().parent

DEFAULT_HERMES_GATEWAY_COMMAND = "hermes gateway start"
DEFAULT_HERMES_HOST = "127.0.0.1"
DEFAULT_HERMES_PORT = 8642
LOCAL_OPENAI_BASE_URL = f"http://{DEFAULT_HERMES_HOST}:{DEFAULT_HERMES_PORT}/v1"
DEFAULT_OPENAI_MODEL = os.getenv("OPENAI_MODEL", "hermes-model")
CARTESIA_VOICE_ID = "71a7ad14-091c-4e8e-a314-022ece01c121"

DEFAULT_CLOUDFLARED_BIN = "cloudflared"
DEFAULT_CLOUDFLARED_WAIT_TIMEOUT_SECS = 90
DEFAULT_CLOUDFLARED_QUICK_TUNNEL = "true"
DEFAULT_CLOUDFLARED_TARGET_URL = f"http://localhost:{DEFAULT_HERMES_PORT}"

DEFAULT_PID_FILE = PROJECT_ROOT / "run" / "bot.pid"
DEFAULT_WAKEWORD_MODEL = "hey jarvis"
DEFAULT_THRESHOLD = 0.5
DEFAULT_COOLDOWN_SECS = 8.0
DEFAULT_VAD_THRESHOLD = 0.5
DEFAULT_INFERENCE_FRAMEWORK = "tflite"

SAMPLE_RATE = 16000
CHUNK_SIZE = 1280